### ISSUE TITLE
Taper A numbers

### ISSUE THREAD

**Issue by opollak** [rabbiabe/MCP4X51_PICO#1]
Line 123 of the cpp file has a last lower bound of 40, I'm guessing that is supposed to be 400

**Comment by rosenbergj** [comment]
For the record: I have no idea what's actually going on here, but I agree with @opollak that it looks wrong, hence the PR.

**Comment by rabbiabe** [comment]
@rosenbergj  [this page has a nice diagram](https://eepower.com/resistor-guide/resistor-types/potentiometer-taper/#) – `TAPER_A` is the blue line, although I used a 4-segment approximation of the true curve instead of the 2-segment approximation used in hardware potentiometers.

**Comment by rosenbergj** [comment]
Got it! I'm a math person and it bugged me that that page didn't have a formula, so I went and found [this explanation](https://electronics.stackexchange.com/a/341052) and I understand much better now! I plugged it into Wolfram Alpha with `y_m = .15` and got [these results](https://www.wolframalpha.com/input?i=y+%3D+%28ab%5E%28x%29+-+a%29*1000%2C+b%3D%28%281%2F.15%29-1%29%5E2%2C+a%3D1%2F%28b-1%29%2C+x%3D.25). If you click "approximate form", it seems that 45 might be slightly better than 50 for starting the second segment, but I don't know whether it would make much of a difference. Thank you for the opportunity to play with logarithms!

**Comment by rabbiabe** [comment]
Totally! the values I used are actually based on experimental measurement of actual potentiometers in my workshop (in case you forgot I'm really a hardware guy, lol) – I measured a bunch of 100kΩ parts used those for the taper percentages. 

The formula you found is very helpful in completing my understanding of the overall model – eyeballing the chart at the bottom, it looks like *y<sub>m</sub>* = 0.1 is `TAPER_A` and the same formula would yield `TAPER_C` when *y<sub>m</sub>* = 0.9. Given the real-world applications for these parts in audio/synth circuits and the MCP4x51's 10MHz clock, there's probably more than enough computing power in the Pico to calculate the taper and offer exact logarithmic sweeps.

On the other hand, given that the 4-segment approximation here is already twice as good of an approximation as the physical devices used in analog applications, I'm content with the code and happy to get back to soldering :)

**Comment by rosenbergj** [comment]
Got it! I used y<sub>m</sub> = 0.15 to get the `TAPER_A` formula because that's what you're implicitly doing by having 150 be the end of the 2nd / start of the 3rd segment. Your curve is between the 0.1 and 0.2 curves. If you wanted 0.1, the formula says you should start the segments at 0, 25, 100, and 325. But I love that you did this experimentally; I'm just having fun with the numbers.
